import { IProduct, ProductType, TasteType } from 'types/products.types';

export const products: IProduct[] = [
    {
        id: 1,
        name: 'Cat Energy',
        type: ProductType.Pro,
        weight: 500,
        taste: TasteType.Chicken,
        price: 700,
        imageSmall: '/img/pictures/catalog-1-small.png',
        imageBig: '/img/pictures/catalog-1-big.png',
        imageSmallRetina: '/img/pictures/catalog-1-small@2x.png',
        imageBigRetina: '/img/pictures/catalog-1-big@2x.png',
    },
    {
        id: 2,
        name: 'Cat Energy',
        type: ProductType.Pro,
        weight: 1000,
        taste: TasteType.Chicken,
        price: 1000,
        imageSmall: '/img/pictures/catalog-2-small.png',
        imageBig: '/img/pictures/catalog-2-big.png',
        imageSmallRetina: '/img/pictures/catalog-2-small@2x.png',
        imageBigRetina: '/img/pictures/catalog-2-big@2x.png',
    },
    {
        id: 3,
        name: 'Cat Energy',
        type: ProductType.Pro,
        weight: 500,
        taste: TasteType.Fish,
        price: 700,
        imageSmall: '/img/pictures/catalog-3-small.png',
        imageBig: '/img/pictures/catalog-3-big.png',
        imageSmallRetina: '/img/pictures/catalog-3-small@2x.png',
        imageBigRetina: '/img/pictures/catalog-3-big@2x.png',
    },
    {
        id: 4,
        name: 'Cat Energy',
        type: ProductType.Pro,
        weight: 1000,
        taste: TasteType.Fish,
        price: 1000,
        imageSmall: '/img/pictures/catalog-4-small.png',
        imageBig: '/img/pictures/catalog-4-big.png',
        imageSmallRetina: '/img/pictures/catalog-4-small@2x.png',
        imageBigRetina: '/img/pictures/catalog-4-big@2x.png',
    },
    {
        id: 5,
        name: 'Cat Energy',
        type: ProductType.Slim,
        weight: 500,
        taste: TasteType.Buckwheat,
        price: 400,
        imageSmall: '/img/pictures/catalog-5-small.png',
        imageBig: '/img/pictures/catalog-5-big.png',
        imageSmallRetina: '/img/pictures/catalog-5-small@2x.png',
        imageBigRetina: '/img/pictures/catalog-5-big@2x.png',
    },
    {
        id: 6,
        name: 'Cat Energy',
        type: ProductType.Slim,
        weight: 1000,
        taste: TasteType.Buckwheat,
        price: 700,
        imageSmall: '/img/pictures/catalog-6-small.png',
        imageBig: '/img/pictures/catalog-6-big.png',
        imageSmallRetina: '/img/pictures/catalog-6-small@2x.png',
        imageBigRetina: '/img/pictures/catalog-6-big@2x.png',
    },
    {
        id: 7,
        name: 'Cat Energy',
        type: ProductType.Slim,
        weight: 500,
        taste: TasteType.Rice,
        price: 500,
        imageSmall: '/img/pictures/catalog-7-small.png',
        imageBig: '/img/pictures/catalog-7-big.png',
        imageSmallRetina: '/img/pictures/catalog-7-small@2x.png',
        imageBigRetina: '/img/pictures/catalog-7-big@2x.png',
    },
];
